import { useRef, useState } from 'react';
import { Alert, Text, View } from 'react-native';
import { BottomSheetModal } from '@gorhom/bottom-sheet';
import { useRouter } from 'expo-router';
import { Card, Chip, PrimaryButton, Screen, SecondaryButton, StatusPill, TimelineItem, sectionTitle } from '../../../components/ui';
import { DepartureSheet } from '../../../sheets/Sheets';
import { mockData, type AttendanceState } from '../../../mock/mockData';
import { useTheme } from '../../../theme/useTheme';
import { spacing, typography } from '../../../theme/tokens';
import { haptics } from '../../../lib/haptics';

export default function Today() {
  const c = useTheme(); const router = useRouter(); const sheet = useRef<BottomSheetModal>(null); const [state, setState] = useState<AttendanceState>(mockData.today.state);
  const next: Record<AttendanceState, { label: string; state: AttendanceState }> = { not_clocked_in: { label: 'Clock in', state: 'working' }, working: { label: 'Start lunch', state: 'on_lunch' }, on_lunch: { label: 'End lunch', state: 'working' }, clocked_out: { label: 'Clock in', state: 'working' } };
  const primary = state === 'clocked_out' ? null : next[state];
  return <Screen><Text style={[typography.footnote, { color: c.textSecondary, marginBottom: 20 }]}>{mockData.today.date}</Text><Text style={[typography.title1, { color: c.textPrimary, marginBottom: 14 }]}>{mockData.employee.name}</Text><Card><Text style={[typography.title2, { color: c.textPrimary }]}>{mockData.today.shift}</Text><Text style={[typography.subhead, { color: c.textSecondary, marginTop: 6 }]}>{mockData.today.site}</Text><Text style={[typography.footnote, { color: c.textSecondary, marginTop: 8 }]}>{mockData.today.start}–{mockData.today.end} · Lunch {mockData.today.lunch}</Text></Card><View style={{ flexDirection: 'row', gap: 8, flexWrap: 'wrap', marginVertical: 18 }}><StatusPill label={state === 'working' ? 'Working' : state === 'on_lunch' ? 'On lunch' : state === 'clocked_out' ? 'Clocked out' : 'Not clocked in'} active={state === 'working'} /><StatusPill label={mockData.today.location} active /></View><PrimaryButton title={primary?.label || 'Shift complete'} disabled={!primary} onPress={() => { if (!primary) return; setState(primary.state); void haptics.success(); Alert.alert('Demo state changed', `${primary.label} is shown locally only. No attendance record was saved.`); }} /><SecondaryButton title="Leave / Go on a job" onPress={() => { void haptics.medium(); sheet.current?.present(); }} />{state === 'working' && <SecondaryButton title="Clock out" onPress={() => { setState('clocked_out'); Alert.alert('Demo state changed', 'Clock out is shown locally only. No attendance record was saved.'); }} />}<View style={{ height: 16 }} /><Card><Text style={sectionTitle(c.textPrimary)}>Today’s timeline</Text>{mockData.today.timeline.map((event, i) => <TimelineItem key={i} {...event} />)}</Card><View style={{ height: 16 }} /><Card><Text style={sectionTitle(c.textPrimary)}>Upcoming job</Text><Text style={[typography.title2, { color: c.textPrimary }]}>{mockData.jobs[0]?.title}</Text><Text style={[typography.footnote, { color: c.textSecondary, marginVertical: 7 }]}>{mockData.jobs[0]?.destination} · {mockData.jobs[0]?.time}</Text><SecondaryButton title="View job" onPress={() => router.push('/job/job-101')} /></Card>{mockData.today.closure && <View style={{ backgroundColor: '#FFF6E7', borderRadius: 16, padding: spacing.lg, marginTop: 16 }}><Chip label="Workplace notice" variant="warning" /><Text style={[typography.subhead, { color: '#63400A', marginTop: 9 }]}>{mockData.today.closure}</Text></View>}<DepartureSheet ref={sheet} onSubmit={() => sheet.current?.dismiss()} /></Screen>;
}
