import React, { useEffect, useState } from 'react';
import { AccessibilityInfo, Pressable, ScrollView, StyleSheet, Text, View, type ViewStyle, type TextStyle } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import Animated, { useAnimatedStyle, useSharedValue, withTiming } from 'react-native-reanimated';
import { Ionicons } from '@expo/vector-icons';
import { haptics } from '../lib/haptics';
import { useTheme } from '../theme/useTheme';
import { hairline, radii, shadows, spacing, typography } from '../theme/tokens';

export function Screen({ children, title, scroll = true }: { children: React.ReactNode; title?: string; scroll?: boolean }) {
  const c = useTheme();
  const body = <>{title && <Text style={[typography.display, { color: c.textPrimary, marginBottom: spacing.xxl }]}>{title}</Text>}{children}</>;
  return <SafeAreaView edges={['bottom']} style={{ flex: 1, backgroundColor: c.bg }}>{scroll ? <ScrollView keyboardDismissMode="interactive" contentInsetAdjustmentBehavior="automatic" contentContainerStyle={{ padding: spacing.lg, paddingBottom: 100 }}>{body}</ScrollView> : body}</SafeAreaView>;
}
export function Card({ children, style }: { children: React.ReactNode; style?: ViewStyle }) { const c = useTheme(); return <View style={[{ backgroundColor: c.surface, borderRadius: radii.card, padding: spacing.lg, ...shadows.card }, style]}>{children}</View>; }
export function StatBlock({ label, value }: { label: string; value: string }) { const c = useTheme(); return <View style={{ flex: 1, gap: 5 }}><Text style={[typography.footnote, { color: c.textSecondary }]}>{label}</Text><Text style={[typography.title1, { color: c.textPrimary }]}>{value}</Text></View>; }
export function Chip({ label, variant = 'neutral' }: { label: string; variant?: 'neutral' | 'accent' | 'warning' | 'success' | 'muted' }) { const c = useTheme(); const colors = variant === 'accent' ? [c.chipAccentBg, c.chipAccentText] : variant === 'warning' ? ['#FFF3DB', c.warning] : variant === 'success' ? ['#E3F5EB', c.success] : variant === 'muted' ? [c.bg, c.textTertiary] : [c.chipNeutralBg, c.chipNeutralText]; return <View style={{ alignSelf: 'flex-start', borderRadius: radii.chip, backgroundColor: colors[0], paddingHorizontal: 10, paddingVertical: 6 }}><Text maxFontSizeMultiplier={1.3} style={[typography.caption, { color: colors[1], fontWeight: '600' }]}>{label}</Text></View>; }
export function StatusPill({ label, active = false }: { label: string; active?: boolean }) { const c = useTheme(); return <View style={{ flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: active ? c.chipAccentBg : c.chipNeutralBg, borderRadius: radii.chip, paddingHorizontal: 10, paddingVertical: 7 }}><View style={{ width: 6, height: 6, borderRadius: 3, backgroundColor: active ? c.accent : c.textTertiary }} /><Text maxFontSizeMultiplier={1.3} style={[typography.caption, { color: active ? c.accent : c.textSecondary, fontWeight: '600' }]}>{label}</Text></View>; }
export function PrimaryButton({ title, onPress, disabled = false }: { title: string; onPress: () => void; disabled?: boolean }) { const c = useTheme(); const scale = useSharedValue(1); const [reduce, setReduce] = useState(false); useEffect(() => { AccessibilityInfo.isReduceMotionEnabled().then(setReduce); }, []); const animated = useAnimatedStyle(() => ({ transform: [{ scale: scale.value }] })); return <Animated.View style={[animated, { width: '100%' }]}><Pressable accessibilityRole="button" disabled={disabled} onPressIn={() => { void haptics.light(); if (!reduce) scale.value = withTiming(0.98, { duration: 120 }); }} onPressOut={() => { if (!reduce) scale.value = withTiming(1, { duration: 120 }); }} onPress={onPress} style={({ pressed }) => ({ height: 56, borderRadius: radii.button, backgroundColor: c.accent, alignItems: 'center', justifyContent: 'center', opacity: disabled ? 0.45 : pressed ? 0.9 : 1 })}><Text style={[typography.bodyEmph, { color: '#FFFFFF' }]}>{title}</Text></Pressable></Animated.View>; }
export function SecondaryButton({ title, onPress }: { title: string; onPress: () => void }) { const c = useTheme(); return <Pressable accessibilityRole="button" onPress={() => { void haptics.light(); onPress(); }} style={({ pressed }) => ({ minHeight: 44, justifyContent: 'center', alignItems: 'center', opacity: pressed ? 0.65 : 1 })}><Text style={[typography.subhead, { color: c.accent, fontWeight: '600' }]}>{title}</Text></Pressable>; }
export function Separator({ inset = 0 }: { inset?: number }) { const c = useTheme(); return <View style={{ height: hairline, backgroundColor: c.separator, marginLeft: inset }} />; }
export function Avatar({ name, size = 32, onPress }: { name: string; size?: 32 | 40 | 56; onPress?: () => void }) { const c = useTheme(); const content = <View style={{ width: size, height: size, borderRadius: size / 2, backgroundColor: c.chipAccentBg, borderWidth: hairline, borderColor: c.separator, alignItems: 'center', justifyContent: 'center' }}><Text style={{ color: c.accent, fontWeight: '600', fontSize: size * 0.36 }}>{name.split(' ').map(p => p[0]).join('').slice(0, 2)}</Text></View>; return onPress ? <Pressable accessibilityLabel="Account settings" accessibilityRole="button" onPress={onPress} hitSlop={6}>{content}</Pressable> : content; }
export function ListRow({ icon, title, subtitle, trailing, onPress }: { icon?: keyof typeof Ionicons.glyphMap; title: string; subtitle?: string; trailing?: React.ReactNode; onPress?: () => void }) { const c = useTheme(); return <Pressable accessibilityRole={onPress ? 'button' : undefined} onPress={onPress} style={({ pressed }) => ({ minHeight: 64, flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 10, opacity: pressed ? 0.65 : 1 })}>{icon && <Ionicons name={icon} size={20} color={c.textSecondary} />}<View style={{ flex: 1, gap: 4 }}><Text style={[typography.subhead, { color: c.textPrimary, fontWeight: '600' }]}>{title}</Text>{subtitle && <Text style={[typography.footnote, { color: c.textSecondary }]}>{subtitle}</Text>}</View>{trailing}{onPress && <Ionicons name="chevron-forward" size={16} color={c.textTertiary} />}</Pressable>; }
export function TimelineItem({ time, label, site, recorded }: { time: string; label: string; site: string; recorded: boolean }) { const c = useTheme(); return <View style={{ flexDirection: 'row', minHeight: 58, gap: 14 }}><Text style={[typography.mono, { color: recorded ? c.textPrimary : c.textSecondary, width: 52, paddingTop: 2 }]}>{time}</Text><View style={{ borderLeftWidth: 2, borderColor: recorded ? c.accent : c.separator, borderStyle: recorded ? 'solid' : 'dashed', paddingLeft: 14, paddingBottom: 12, flex: 1 }}><Text style={[typography.subhead, { color: recorded ? c.textPrimary : c.textSecondary, fontWeight: '600' }]}>{label}</Text><Text style={[typography.footnote, { color: c.textTertiary, marginTop: 3 }]}>{site}</Text></View></View>; }
export function EmptyState({ icon, title, description, action, onAction }: { icon: keyof typeof Ionicons.glyphMap; title: string; description: string; action?: string; onAction?: () => void }) { const c = useTheme(); return <View style={{ padding: 32, alignItems: 'center', gap: 8 }}><Ionicons name={icon} size={32} color={c.textTertiary} /><Text style={[typography.title2, { color: c.textPrimary }]}>{title}</Text><Text style={[typography.footnote, { color: c.textSecondary, textAlign: 'center' }]}>{description}</Text>{action && onAction && <SecondaryButton title={action} onPress={onAction} />}</View>; }
export function Skeleton({ height = 72 }: { height?: number }) { const c = useTheme(); const opacity = useSharedValue(0.45); const [reduce, setReduce] = useState(false); useEffect(() => { AccessibilityInfo.isReduceMotionEnabled().then(setReduce); }, []); useEffect(() => { if (!reduce) opacity.value = withTiming(0.75, { duration: 600 }); }, [reduce, opacity]); const animated = useAnimatedStyle(() => ({ opacity: opacity.value })); return <Animated.View style={[animated, { height, borderRadius: radii.card, backgroundColor: c.separator }]} />; }
export const sectionTitle = (color: string): TextStyle => ({ ...typography.title2, color, marginBottom: 12 });
