import React, { forwardRef, useCallback, useMemo, useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, Pressable, Text, TextInput, View } from 'react-native';
import { BottomSheetBackdrop, BottomSheetModal, BottomSheetScrollView } from '@gorhom/bottom-sheet';
import DateTimePicker from '@react-native-community/datetimepicker';
import { Ionicons } from '@expo/vector-icons';
import SegmentedControl from '@react-native-segmented-control/segmented-control';
import { Card, PrimaryButton, Separator } from '../components/ui';
import { mockData } from '../mock/mockData';
import { useTheme } from '../theme/useTheme';
import { radii, spacing, typography } from '../theme/tokens';
import { haptics } from '../lib/haptics';

type SheetRef = BottomSheetModal;
function BaseSheet({ children, title, points, onClose }: { children: React.ReactNode; title: string; points: string[]; onClose?: () => void }) {
  const c = useTheme(); return <BottomSheetScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ paddingHorizontal: spacing.xxl, paddingBottom: 44 }}><Text style={[typography.title1, { color: c.textPrimary, marginBottom: 20 }]}>{title}</Text>{children}</BottomSheetScrollView>;
}
export const MissingPunchSheet = forwardRef<SheetRef, { onSubmit?: () => void }>(function MissingPunchSheet({ onSubmit }, ref) {
  const c = useTheme(); const [type, setType] = useState(0); const [date, setDate] = useState(new Date()); const [reason, setReason] = useState(''); const [note, setNote] = useState('');
  const backdrop = useCallback((props: any) => <BottomSheetBackdrop {...props} appearsOnIndex={0} disappearsOnIndex={-1} pressBehavior="close" opacity={0.4} />, []);
  return <BottomSheetModal ref={ref} index={0} snapPoints={['45%', '85%']} enablePanDownToClose backdropComponent={backdrop} backgroundStyle={{ backgroundColor: c.surfaceElevated, borderTopLeftRadius: radii.sheet, borderTopRightRadius: radii.sheet }} handleIndicatorStyle={{ width: 36, height: 5, backgroundColor: c.separator }}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined}><BaseSheet title="Report missing punch" points={['45%', '85%']}><SegmentedControl values={['Forgot clock in', 'Forgot clock out']} selectedIndex={type} onChange={e => { setType(e.nativeEvent.selectedSegmentIndex); void haptics.selection(); }} tintColor={c.surface} backgroundColor={c.chipNeutralBg} /><Text style={[typography.footnote, { color: c.textSecondary, marginTop: 22 }]}>Time</Text><DateTimePicker value={date} mode="time" display={Platform.OS === 'ios' ? 'compact' : 'default'} onChange={(_, next) => next && setDate(next)} /><Text style={[typography.footnote, { color: c.textSecondary, marginTop: 16 }]}>Reason</Text><TextInput value={reason} onChangeText={setReason} placeholder="Tell your manager what happened" placeholderTextColor={c.textTertiary} multiline style={{ minHeight: 84, backgroundColor: c.bg, borderRadius: 12, padding: 12, color: c.textPrimary, marginTop: 8, textAlignVertical: 'top' }} /><Text style={[typography.footnote, { color: c.textSecondary, marginTop: 16 }]}>Note (optional)</Text><TextInput value={note} onChangeText={setNote} placeholder="Add context" placeholderTextColor={c.textTertiary} style={{ minHeight: 44, backgroundColor: c.bg, borderRadius: 12, padding: 12, color: c.textPrimary, marginTop: 8 }} /><View style={{ height: 20 }} /><PrimaryButton title="Submit for approval" disabled={!reason.trim()} onPress={() => { void haptics.success(); Alert.alert('Demo only', 'This correction was not submitted.'); onSubmit?.(); }} /></BaseSheet></KeyboardAvoidingView></BottomSheetModal>;
});
export const DepartureSheet = forwardRef<SheetRef, { onSubmit?: () => void }>(function DepartureSheet({ onSubmit }, ref) {
  const c = useTheme(); const [reason, setReason] = useState<'job' | 'personal' | 'emergency'>('job'); const [job, setJob] = useState(mockData.jobs[0]?.id || ''); const [date, setDate] = useState(new Date()); const [note, setNote] = useState('');
  const backdrop = useCallback((props: any) => <BottomSheetBackdrop {...props} appearsOnIndex={0} disappearsOnIndex={-1} pressBehavior="close" opacity={0.4} />, []);
  return <BottomSheetModal ref={ref} index={0} snapPoints={['45%', '85%']} enablePanDownToClose backdropComponent={backdrop} backgroundStyle={{ backgroundColor: c.surfaceElevated, borderTopLeftRadius: radii.sheet, borderTopRightRadius: radii.sheet }} handleIndicatorStyle={{ width: 36, height: 5, backgroundColor: c.separator }}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined}><BaseSheet title="Leave / Go on a job" points={['45%', '85%']}>{([['job', 'Assigned job'], ['personal', 'Personal departure'], ['emergency', 'Emergency']] as const).map(([value, label]) => <Pressable key={value} accessibilityRole="radio" accessibilityState={{ checked: reason === value }} onPress={() => { setReason(value); void haptics.selection(); }} style={{ minHeight: 50, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }}><Text style={[typography.subhead, { color: c.textPrimary }]}>{label}</Text><Ionicons name={reason === value ? 'radio-button-on' : 'radio-button-off'} size={22} color={reason === value ? c.accent : c.textTertiary} /></Pressable>)}{reason === 'job' && mockData.jobs.filter(j => j.status !== 'Completed').map(j => <Pressable key={j.id} onPress={() => setJob(j.id)} style={{ minHeight: 44, paddingLeft: 16, flexDirection: 'row', alignItems: 'center', gap: 8 }}><Ionicons name={job === j.id ? 'checkmark-circle' : 'ellipse-outline'} size={18} color={c.accent} /><Text style={[typography.footnote, { color: c.textSecondary }]}>{j.title}</Text></Pressable>)}<Separator /><View style={{ marginTop: 18, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }}><Text style={[typography.subhead, { color: c.textPrimary }]}>Expected return</Text><DateTimePicker value={date} mode="time" display={Platform.OS === 'ios' ? 'compact' : 'default'} onChange={(_, next) => next && setDate(next)} /></View><TextInput value={note} onChangeText={setNote} placeholder="Short note (optional)" placeholderTextColor={c.textTertiary} style={{ minHeight: 48, backgroundColor: c.bg, borderRadius: 12, padding: 12, color: c.textPrimary, marginTop: 18 }} /><View style={{ flexDirection: 'row', alignItems: 'center', gap: 6, marginVertical: 20 }}><Ionicons name="information-circle-outline" size={16} color={c.textSecondary} /><Text style={[typography.footnote, { color: c.textSecondary }]}>Manager approval required</Text></View><PrimaryButton title="Confirm departure" onPress={() => { void haptics.success(); Alert.alert('Demo only', 'This departure was not submitted.'); onSubmit?.(); }} /></BaseSheet></KeyboardAvoidingView></BottomSheetModal>;
});
