/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HoursRouteImport } from './routes/hours'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as RequestsRouteImport } from './routes/requests'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HoursRoute = HoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hours': typeof HoursRoute
  '/jobs': typeof JobsRoute
  '/manager': typeof ManagerRoute
  '/requests': typeof RequestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hours': typeof HoursRoute
  '/jobs': typeof JobsRoute
  '/manager': typeof ManagerRoute
  '/requests': typeof RequestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hours': typeof HoursRoute
  '/jobs': typeof JobsRoute
  '/manager': typeof ManagerRoute
  '/requests': typeof RequestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/hours' | '/jobs' | '/manager' | '/requests'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hours' | '/jobs' | '/manager' | '/requests'
  id: '__root__' | '/' | '/hours' | '/jobs' | '/manager' | '/requests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HoursRoute: typeof HoursRoute
  JobsRoute: typeof JobsRoute
  ManagerRoute: typeof ManagerRoute
  RequestsRoute: typeof RequestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hours': {
      id: '/hours'
      path: '/hours'
      fullPath: '/hours'
      preLoaderRoute: typeof HoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HoursRoute: HoursRoute,
  JobsRoute: JobsRoute,
  ManagerRoute: ManagerRoute,
  RequestsRoute: RequestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
